### ISSUE TITLE
Question for the paper

### ISSUE THREAD

**Issue by HenryCai11** [AOZMH/Crake#1]
Hi there,

Thank you for your great work! I have a question about the explanation of Algorithm 1 in section 4. I am confused about the sentence "... retrieve its candidates P based on G (e.g. G already entails `?class=dbr:bird`, so all neighbors of `dbr:bird` forms P), ...", where the "dbr:bird" appears for the first time and is not included in any figures. Is this a typo, or is it just an example of what forms P when G entails `?class=dbr:bird`?

Thanks in advance!

**Comment by AOZMH** [comment]
Hello,

Thx for your interest on our work! As for your question, the second explanation is correct (it illustrates how we retrieve candidate predicates P when both nodes it connects are variables).

Actually, this example is intended to correspond to the case in Fig. 1, 2 & 4, in which the variable `?class` should be `dbr:bird` when we query the SPARQL in KB (since the class of Swinhoe's Crake is bird). When we deal with the node pair `?class-?person`, since both nodes are variables (not entity or type), we cannot directly obtain its candidate predicates by query the adjacent edges of certain node(s) in KB. However, since we've already filled in the predicate `dbp:class` between `?class-dbr:Swinhoe’s_Crake`, we already know that `dbr:bird` binds to `?class` (as the triple `dbr:Swinhoe’s_Crake - dbp:class - dbr:bird` exists in KB), which means the candidates of `?class-?person` could now be the adjacencies of `dbr:bird`, including the correct predicate `dbp:named_by`. With this process, we obtain the candidates between two variables and by ranking & selecting these candidates we can determine the candidates of other "variable-variable" node pairs until all edges are determined.

Hence, the sentence you mentioned is intended to explain the RE process in Fig. 1, 2 & 4. However, I guess your confusion comes from a typo right above your sentence, which should actually be "... select the most proper predicate p1 (e.g. **dbp:class**) ...". We sincerely apologize for this mistake and expect to correct this in a new Arxiv version. Besides, we hope this explanation could address your confusion. Pls feel free to contact us for any further concerns, thx again!

**Comment by HenryCai11** [comment]
Thanks for your reply. That really helps a lot!
